name: tensorflow-api
version: "1.00"
summary: Image recognition tensorflow API snap
description: API for image recognition.
  Uses JavaFX for capture images from web cam and TensorFlow library for images recognition (http://www.tensorflow.org/).
confinement: strict
grade: devel

apps:
  tensorflow-api-daemond:
    command: python2 $SNAP/rest_api.py --api-key 123
    daemon: simple
    plugs: [network, network-bind]

parts:
  tensorflow-pip-python3:
    plugin: python
    python-version: python2
    source: .
    python-packages: [werkzeug, flask, six, funcsigs, pbr, mock, numpy, appdirs, pyparsing, packaging, setuptools, protobuf, wheel, tensorflow]

  tensorflow-rest-api:
    plugin: dump
    source: api

  imagenet-data:
    plugin: dump
    source: imagenet
    filesets:
      imagenet: [classify_image_graph_def.pb, -cropped_panda.jpg, imagenet_2012_challenge_label_map_proto.pbtxt, imagenet_synset_to_human_label_map.txt, LICENSE]
#    organize:
#      $imagenet: imagenet/
