name: maskburster
version: '0.1'
summary: ski mask detection app
description: |
  The goal of the demo is show a use case how artificial intelligence
  connected to various devices could bring additional value and, as an
  example from this demo, improve on the public safety.
  The scene for this demo is as follows. Imagine there’s a webcam in an
  elevator, connected to an intelligent image recognition service. If
  the software detects a person with malicious intentions – for the
  purpose of our demo, it would be a person in a ski mask – then it
  flashes the screen for the personnel who is watching the web cam,
  turns on a siren light for a short period of time and makes a phone call.

grade: devel
confinement: devmode

apps:
  maskburster:
    command: desktop-launch $SNAP/start.sh
    plugs: [network, network-bind, x11, camera, opengl, home]

parts:
  webserver:
    source: ./js_src
    plugin: nodejs
    node-engine: "7.5.0"
    stage-packages: [openjdk-8-jre, openjfx, libv4l-dev]
    after: [desktop-gtk2]
    install: |
      echo "#!/bin/bash" > ../install/start.sh
      echo "export LD_LIBRARY_PATH=\$SNAP/usr/lib/x86_64-linux-gnu/dri:\$LD_LIBRARY_PATH"  >> ../install/start.sh
      echo "\$SNAP/bin/maskburster \$SNAP/lib/node_modules/maskburster/" >> ../install/start.sh
      chmod +x ../install/start.sh

